<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net48</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HarpoS7" Version="$(PackageVersion)" />
        <PackageReference Include="HarpoS7.PublicKeys" Version="$(PackageVersion)" />
    </ItemGroup>

</Project>
